"""Verify the unapplied consumer patch without changing production source."""
from pathlib import Path
import hashlib
import json
import re
import subprocess
import sys


def candidate(base, patch):
    lines = base.splitlines(True)
    result = []
    position = 0
    active = False
    for line in patch.splitlines(True):
        if line.startswith("@@"):
            start = int(re.match(r"@@ -(\d+)", line)[1]) - 1
            result.extend(lines[position:start])
            position = start
            active = True
        elif active and line.startswith((" ", "-", "+")):
            if line[0] != "+":
                assert lines[position] == line[1:], (position, line)
                position += 1
            if line[0] != "-":
                result.append(line[1:])
    result.extend(lines[position:])
    return "".join(result)


def prepare_source_gate(receipt, proposed, supplier):
    """Compile exact scope functions and proposed tests, not a mock kernel."""
    start = proposed.index("const MAX_ANCESTRY_DEPTH:")
    end = proposed.index("/// The scope prefix every app-tier", start)
    tests = proposed[proposed.index("#[cfg(test)]\nmod resource_capture_tests"):]
    prelude = """// Generated by verify_patch.py from the recorded consumer patch.
extern crate self as mere;
pub use kernel;
use kernel::graph::Graph;
use kernel::graph::capture::CapturedDelta;
use servitor::ScopePath;
use std::collections::HashSet;

"""
    gate = receipt / "consumer_gate"
    (gate / "src").mkdir(parents=True, exist_ok=True)
    (gate / "src/lib.rs").write_bytes((prelude + proposed[start:end] + tests).encode())
    kernel = (supplier / "crates/graph/graph-kernel").as_posix()
    servitor = (supplier / "crates/servitor").as_posix()
    manifest = f"""[package]
name = "turnstone-resource-capture-gate"
version = "0.0.0"
edition = "2024"
publish = false

[workspace]

[dependencies]
kernel = {{ package = "mere-kernel", path = "{kernel}" }}
servitor = {{ path = "{servitor}" }}
uuid = "1"
"""
    (gate / "Cargo.toml").write_bytes(manifest.encode())


if __name__ == "__main__":
    receipt = Path(__file__).resolve().parent
    root = receipt.parents[2]
    preparation = json.loads((receipt / "preparation.json").read_text())
    source = root / "src/behaviors.rs"
    patch_path = receipt / "behaviors.patch"
    assert hashlib.sha256(source.read_bytes()).hexdigest() == preparation["consumer_base_sha256"]
    assert hashlib.sha256(patch_path.read_bytes()).hexdigest() == preparation["patch_sha256"]
    proposed = candidate(source.read_text(), patch_path.read_text())
    assert hashlib.sha256(proposed.encode()).hexdigest() == preparation["candidate_sha256_lf"]
    subprocess.run(["git", "apply", "--check", str(patch_path)], cwd=root, check=True)
    subprocess.run(
        ["rustfmt", "--edition", "2024", "--emit", "stdout"],
        input=proposed.encode(), stdout=subprocess.DEVNULL, check=True,
    )
    if sys.argv[1:] == ["--prepare-source-gate"]:
        prepare_source_gate(receipt, proposed, Path(preparation["supplier_path"]))
        print("Prepared exact scope-function fixture against supplier path; no application or pin change.")
    elif sys.argv[1:]:
        raise SystemExit("Usage: verify_patch.py [--prepare-source-gate]")
    print("Verified hashes, patch applicability and Rust parsing; no compilation or regression claim.")
