// Generated by verify_patch.py from the recorded consumer patch.
extern crate self as mere;
pub use kernel;
use kernel::graph::Graph;
use kernel::graph::capture::CapturedDelta;
use servitor::ScopePath;
use std::collections::HashSet;

const MAX_ANCESTRY_DEPTH: usize = 32;

/// The currently affected surface ids a delta touches.
///
/// Resource records and pairs expand through explicit shown-resource identity;
/// surface captures keep their exact target. Record metadata is not inspected.
///
/// Exhaustive by construction: a new `CapturedDelta` variant fails to compile
/// here until it is classified, which is the same discipline `ring_of` uses
/// for actions. A variant that silently touched nothing would be a behavior
/// that silently stopped waking.
pub fn touched_ids(graph: &Graph, delta: &CapturedDelta) -> Vec<String> {
    use CapturedDelta as D;
    let ids = match delta {
        D::ReplayAddNodeWithIdIfMissing { id, .. } => vec![id.as_str()],

        D::ReplayRemoveNodeById { node_id, .. }
        | D::ReplaySetNodeTitleById { node_id, .. }
        | D::ReplaySetNodeUrlById { node_id, .. }
        | D::ReplaySetNodeImageById { node_id, .. }
        | D::ReplaySetNodeThumbnailById { node_id, .. }
        | D::ReplaySetNodeFaviconById { node_id, .. }
        | D::ReplaySetNodeMimeHintById { node_id, .. }
        | D::ReplaySetNodeContentById { node_id, .. }
        | D::ReplaySetNodeNestedById { node_id, .. }
        | D::ReplaySetNodePinnedById { node_id, .. }
        | D::ReplaySetNodeFacetById { node_id, .. }
        | D::ReplayRemoveNodeFacetById { node_id, .. }
        | D::ReplayInsertNodeTagById { node_id, .. }
        | D::ReplayRemoveNodeTagById { node_id, .. }
        | D::ReplaySetNodeBodyById { node_id, .. }
        | D::ReplayNavigateNodeById { node_id, .. }
        | D::ReplayNodeHistoryBackById { node_id, .. }
        | D::ReplayNodeHistoryForwardById { node_id, .. }
        | D::ReplayAppendNodePropertyById { node_id, .. }
        | D::ReplayAddNodeClassificationById { node_id, .. }
        | D::ReplayRemoveNodeClassificationById { node_id, .. }
        | D::ReplaySetNodeClassificationStatusById { node_id, .. }
        | D::ReplaySetNodePrimaryClassificationById { node_id, .. }
        | D::ReplayRecordNodeDerivationById { node_id, .. }
        | D::ReplaySetNodeTagIconOverrideById { node_id, .. }
        | D::ReplayAppendFrameLayoutHintById { node_id, .. }
        | D::ReplayRemoveFrameLayoutHintById { node_id, .. }
        | D::ReplayMoveFrameLayoutHintById { node_id, .. }
        | D::ReplaySetFrameSplitOfferSuppressedById { node_id, .. }
        | D::ReplayUpdateNodeHistoryById { node_id, .. }
        | D::ReplayTouchNodeLastVisitedById { node_id, .. } => vec![node_id.as_str()],

        D::ReplayAssertRelationByIds { from_id, to_id, .. }
        | D::ReplayRetractRelationsByIds { from_id, to_id, .. }
        | D::ReplayAppendTraversalByIds { from_id, to_id, .. }
        | D::ReplaySetEdgesByIds { from_id, to_id, .. }
        | D::ReplaySetEdgeSemanticPredicateByIds { from_id, to_id, .. }
        | D::ReplayAssertSemanticPredicateByIds { from_id, to_id, .. } => {
            vec![from_id.as_str(), to_id.as_str()]
        }

        D::ReplayBranchHistoryByIds {
            child_id,
            parent_id,
        } => vec![child_id.as_str(), parent_id.as_str()],

        D::ReplaySetResourceRecordById { resource_id, .. } => {
            return surfaces_for_resources(graph, &[resource_id.as_str()]);
        }
        D::ReplaySetResourceEdgesByIds {
            from_resource_id,
            to_resource_id,
            ..
        } => {
            return surfaces_for_resources(
                graph,
                &[from_resource_id.as_str(), to_resource_id.as_str()],
            );
        }
        D::ReplaySetShownResourceById { surface_id, .. } => vec![surface_id.as_str()],

        // Session-level and field/coupling deltas name no node. The physics
        // tier is deliberately outside this vocabulary: spatial influence
        // reaches the graph through fields, never through a petition, so a
        // field change is not a thing a behavior is woken by.
        D::ReplaySetImportRecords { .. }
        | D::ReplayAddField { .. }
        | D::ReplayRetireFieldById { .. }
        | D::ReplayRemoveFieldById { .. }
        | D::ReplayAddCoupling { .. }
        | D::ReplaySetFieldCouplingStrengthByFieldId { .. }
        | D::ReplayActivateFieldById { .. }
        | D::ReplayRetractCouplingById { .. } => Vec::new(),
    };
    ids.into_iter().map(str::to_owned).collect()
}

/// Resource identities are not behavior scopes. Resolve them through the
/// graph's current shown-resource mapping, then deduplicate before ancestry.
fn surfaces_for_resources(graph: &Graph, resources: &[&str]) -> Vec<String> {
    resources
        .iter()
        .filter_map(|id| id.parse::<uuid::Uuid>().ok())
        .flat_map(|id| graph.surface_ids_showing_resource(id))
        .collect::<std::collections::BTreeSet<_>>()
        .into_iter()
        .map(|id| id.to_string())
        .collect()
}

/// Every containment ancestry of `id`, each as a root-first scope path ending
/// in the node itself.
///
/// A node with no container is its own single-segment scope, which is also
/// what a node the graph no longer holds falls back to.
pub fn ancestry_scopes(graph: &Graph, id: &str) -> Vec<ScopePath> {
    let Ok(uuid) = id.parse::<uuid::Uuid>() else {
        return Vec::new();
    };
    let Some(key) = graph.get_node_key_by_id(uuid) else {
        // Removed, or never present: the bare id is all there is to say.
        return ScopePath::parse(id).into_iter().collect();
    };

    // Containment runs member -> container, so a node's containers are its
    // outgoing containment targets.
    let mut paths: Vec<Vec<String>> = Vec::new();
    let mut frontier: Vec<(Vec<String>, mere::kernel::graph::NodeKey, HashSet<String>)> = {
        let mut seen = HashSet::new();
        seen.insert(id.to_string());
        vec![(vec![id.to_string()], key, seen)]
    };

    while let Some((path, at, seen)) = frontier.pop() {
        let containers: Vec<_> = graph
            .containment_edges()
            .filter(|edge| edge.from == at)
            .map(|edge| edge.to)
            .collect();
        let mut grew = false;
        for container in containers {
            let Some(node) = graph.get_node(container) else {
                continue;
            };
            let container_id = node.id.to_string();
            if seen.contains(&container_id) || path.len() >= MAX_ANCESTRY_DEPTH {
                // A cycle, or deeper than a scope is worth. The path so far is
                // still a real region, so it is kept rather than dropped.
                continue;
            }
            let mut next = path.clone();
            next.push(container_id.clone());
            let mut seen = seen.clone();
            seen.insert(container_id);
            frontier.push((next, container, seen));
            grew = true;
        }
        if !grew {
            paths.push(path);
        }
    }

    // Built leaf-first while walking; a scope reads outermost-first.
    paths
        .into_iter()
        .filter_map(|mut path| {
            path.reverse();
            ScopePath::parse(&path.join("/")).ok()
        })
        .collect()
}

#[cfg(test)]
mod resource_capture_tests {
    use super::*;
    use mere::kernel::graph::apply::apply_graph_delta;

    fn add_surface(graph: &mut Graph, serial: u128, url: &str) -> (uuid::Uuid, uuid::Uuid) {
        let surface = uuid::Uuid::from_u128(serial);
        let capture = CapturedDelta::ReplayAddNodeWithIdIfMissing {
            id: surface.to_string(),
            url: url.into(),
            position: [0.0, 0.0],
        };
        apply_graph_delta(graph, capture.replay_delta().unwrap());
        let resource = mere::kernel::graph::ResourceNode::new(url);
        let record = CapturedDelta::ReplaySetResourceRecordById {
            resource_id: resource.id().to_string(),
            record: Some(mere::kernel::persistence::PersistedResourceRecord {
                canonical_iri: resource.canonical_iri().into(),
                facets: Vec::new(),
            }),
        };
        apply_graph_delta(graph, record.replay_delta().unwrap());
        let shown = CapturedDelta::ReplaySetShownResourceById {
            surface_id: surface.to_string(),
            resource_id: Some(resource.id().to_string()),
        };
        apply_graph_delta(graph, shown.replay_delta().unwrap());
        let key = graph.get_node_key_by_id(surface).unwrap();
        (surface, graph.shown_resource_id(key).unwrap())
    }

    fn aliases(graph: &mut Graph) -> (uuid::Uuid, uuid::Uuid, uuid::Uuid) {
        let (first, resource) = add_surface(graph, 1, "https://example.org/page?id=1");
        let (second, alias) = add_surface(
            graph,
            2,
            "https://EXAMPLE.ORG:443/page?utm_source=news&id=1#fragment",
        );
        assert_eq!(resource, alias);
        (first, second, resource)
    }

    fn resource_change(resource: uuid::Uuid) -> CapturedDelta {
        CapturedDelta::ReplaySetResourceRecordById {
            resource_id: resource.to_string(),
            record: None,
        }
    }

    #[test]
    fn a_resource_record_wakes_all_alias_surfaces_and_not_an_unrelated_surface() {
        let mut graph = Graph::new();
        let (first, second, resource) = aliases(&mut graph);
        let (unrelated, _) = add_surface(&mut graph, 3, "https://example.org/other");
        let ids = touched_ids(&graph, &resource_change(resource));
        assert_eq!(ids, vec![first.to_string(), second.to_string()]);
        assert!(!ids.contains(&unrelated.to_string()));
    }

    #[test]
    fn resource_pairs_union_both_endpoint_surfaces_and_deduplicate_self_pairs() {
        let mut graph = Graph::new();
        let (first, second, resource) = aliases(&mut graph);
        let (third, other) = add_surface(&mut graph, 3, "https://example.org/other");
        let pair = |to: uuid::Uuid| CapturedDelta::ReplaySetResourceEdgesByIds {
            from_resource_id: resource.to_string(),
            to_resource_id: to.to_string(),
            edges: Vec::new(),
        };
        assert_eq!(
            touched_ids(&graph, &pair(other)),
            vec![first.to_string(), second.to_string(), third.to_string()]
        );
        assert_eq!(
            touched_ids(&graph, &pair(resource)),
            vec![first.to_string(), second.to_string()]
        );
    }

    #[test]
    fn malformed_or_unshown_resource_ids_do_not_become_bare_surface_wakes() {
        let mut graph = Graph::new();
        let (first, second, resource) = aliases(&mut graph);
        let malformed = CapturedDelta::ReplaySetResourceRecordById {
            resource_id: "not-a-resource-uuid".into(),
            record: None,
        };
        assert!(touched_ids(&graph, &malformed).is_empty());
        assert!(touched_ids(&graph, &resource_change(uuid::Uuid::from_u128(99))).is_empty());
        let pair = CapturedDelta::ReplaySetResourceEdgesByIds {
            from_resource_id: "invalid".into(),
            to_resource_id: resource.to_string(),
            edges: Vec::new(),
        };
        assert_eq!(
            touched_ids(&graph, &pair),
            vec![first.to_string(), second.to_string()]
        );
    }

    #[test]
    fn shown_resource_retarget_and_clear_wake_only_the_named_surface() {
        let mut graph = Graph::new();
        let (first, second, old_resource) = aliases(&mut graph);
        let (third, new_resource) = add_surface(&mut graph, 3, "https://example.org/other");
        for shown in [Some(new_resource.to_string()), None] {
            let capture = CapturedDelta::ReplaySetShownResourceById {
                surface_id: first.to_string(),
                resource_id: shown.clone(),
            };
            apply_graph_delta(&mut graph, capture.replay_delta().unwrap());
            assert_eq!(touched_ids(&graph, &capture), vec![first.to_string()]);
            assert_eq!(
                touched_ids(&graph, &resource_change(old_resource)),
                vec![second.to_string()]
            );
            let expected_new = if shown.is_some() {
                vec![first.to_string(), third.to_string()]
            } else {
                vec![third.to_string()]
            };
            assert_eq!(
                touched_ids(&graph, &resource_change(new_resource)),
                expected_new
            );
        }
    }

    #[test]
    fn legacy_surface_and_exact_edge_captures_keep_their_targets() {
        let graph = Graph::new();
        let first = uuid::Uuid::from_u128(1).to_string();
        let second = uuid::Uuid::from_u128(2).to_string();
        let old = CapturedDelta::ReplaySetEdgesByIds {
            from_id: first.clone(),
            to_id: second.clone(),
            edges: Vec::new(),
        };
        assert_eq!(touched_ids(&graph, &old), vec![first.clone(), second]);
        let removed = CapturedDelta::ReplayRemoveNodeById {
            node_id: first.clone(),
        };
        assert_eq!(touched_ids(&graph, &removed), vec![first.clone()]);
        assert_eq!(ancestry_scopes(&graph, &first)[0].segments(), &[first]);
        assert!(ancestry_scopes(&graph, "invalid-surface").is_empty());
    }

    #[test]
    fn expanded_surface_scopes_keep_watch_matching_and_no_self_wake() {
        let mut graph = Graph::new();
        let (first, second, resource) = aliases(&mut graph);
        let subject = servitor::Subject::new([0x31; 32]);
        let scopes = touched_ids(&graph, &resource_change(resource))
            .into_iter()
            .flat_map(|id| ancestry_scopes(&graph, &id))
            .collect::<Vec<_>>();
        let human = servitor::cascade::CommittedEntry::new(1, "human", scopes.clone());
        let own = servitor::cascade::CommittedEntry::new(2, subject.to_hex(), scopes);
        for surface in [first, second] {
            let watch = servitor::Watch {
                subject,
                scope: servitor::ScopePath::parse(&surface.to_string()).unwrap(),
                self_author: subject.to_hex(),
                cursor: 0,
            };
            assert!(watch.matches(&human.as_event()));
            assert!(!watch.matches(&own.as_event()));
        }
    }
}
